### PR TITLE
Integration with Docker

### PR DESCRIPTION
**Pull request by sevein**
https://jiscdev.atlassian.net/browse/RDSSARK-18

See commits for more details.

### CODE REVIEW

**Review by fractos — COMMENTED** [review]
The storage service logs are emitted only to console now?

**Comment by sevein** [comment]
> The storage service logs are emitted only to console now?

@fractos yes, that worked pretty well for Docker Compose which aggregates the standard streams of all the services. It seems that it could also work in ECS but we can also setup new handlers if needed. Would that work?

**Comment by fractos** [comment]
Hi @sevein - Yes, I believe so. It looks like the container console can be routed through to a CloudWatch log - http://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_awslogs.html

**Comment by sevein** [comment]
Cool, I really like that idea!

**Review by helenst — COMMENTED** [review]
This is great! :+1: Using rdss-archivematica repo, I was able to get up and running with this (and get the shibboleth branch based onto it) very quickly. The code looks good to me.

**Comment by lower29** [comment]
I have nothing further to add, it's working for me too.

**Pull request merged**
