### PR TITLE
Delete create_testuser

### LINKED ISSUE #12: Problem: test user is always created
This should be deleted: https://github.com/JiscRDSS/archivematica-storage-service/blob/6c52e567e0ee075d7ef4746e27ac8767b5eea69e/storage_service/common/models.py#L14-L25

Users are now created using the `create_user` command.

### PR DESCRIPTION
**Pull request by sevein**
This closes #12.

### CODE REVIEW

**Comment by sevein** [comment]
@helenst, should I leave the `models.py` file empty or delete it? We're using Django 1.8. I remember at some point the convention changed but I couldn't find it in the docs.

**Comment by helenst** [comment]
@sevein You can delete it - that changed in Django 1.7 as part of the app loading refactor https://docs.djangoproject.com/en/1.11/releases/1.7/#app-loading-refactor

**Comment by sevein** [comment]
Thanks, done!

**Review by helenst — APPROVED** [review]
This looks good to me! (and another one to port across to core)

**Pull request merged**
